name=MentorBit-Library
version=1.1.0
author=Digital Codesign
maintainer=Digital Codesign
sentence=Librería para MentorBit
paragraph=Conjunto de valores y funciones para facilitar su uso y testeo
category=Other
url=https://github.com/DigitalCodesign/MentorBit-Library
architectures=*
depends=Adafruit BusIO, Adafruit GFX Library, Adafruit SSD1306, OneWire, SD, Servo
